# AKshare获取指数数据

In [1]:
import akshare as ak

stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(
    symbol="sh000016", start_date="20250101", end_date="20250801"
)
data = stock_zh_a_daily_qfq_df[
    ["date", "open", "high", "low", "close", "volume", "amount"]
].rename(
    columns={
        "open": "OPEN",
        "high": "HIGH",
        "low": "LOW",
        "close": "CLOSE",
        "volume": "VLOUME",
        "amount": "AMT",
    }
)
data["PCT_CHG"] = data["CLOSE"].pct_change() * 100

# wind指数网站获取指数数据

In [ ]:
import requests
import pandas as pd

# https://www.windindices.com/indices/zh/IndexF9/e2d5a98547c3ee7c923a0259cee963e4
url = "https://indexapi.wind.com.cn/indicesWebsite/api/Kline?indexId=6644c422b6edae80b3c7a7d55803bc9e&period=1Y&lan=cn"
res = requests.get(url)
data = pd.DataFrame(res.json()["Result"]["data"])
data = data[["tradeDate", "open", "hight", "low", "close", "pctChange", "volume", "amount"]]

In [50]:
data.rename(
    columns={
        "tradeDate": "date",
        "open": "OPEN",
        "hight": "HIGH",
        "low": "LOW",
        "close": "CLOSE",
        "pctChange": "PCT_CHG",
        "volume": "VOLUME",
        "amount": "AMT",
    }
)

,date,OPEN,HIGH,LOW,CLOSE,PCT_CHG,VOLUME,AMT
0,20240802,221794.4531,223606.9219,219783.7344,219973.1719,-1.328707,2.275304e+09,1.232747e+10
1,20240805,218919.7813,222168.5781,215101.4688,215103.7969,-2.213622,2.472553e+09,1.318106e+10
2,20240806,217058.5469,221364.8750,217058.5469,221364.8750,2.910724,2.174654e+09,1.163576e+10
3,20240807,221867.2813,222546.5781,220096.0469,221525.6094,0.072611,2.078274e+09,1.129093e+10
4,20240808,221106.7344,222534.5156,217900.0156,221980.3594,0.205281,2.539888e+09,1.315276e+10
...,...,...,...,...,...,...,...,...
237,20250728,470595.2449,475328.4805,470525.9424,475130.5151,1.055302,3.196147e+09,3.797102e+10
238,20250729,476736.9756,476900.6297,469715.3937,474585.7004,-0.114666,3.461563e+09,4.061039e+10
239,20250730,474047.3739,476330.8669,470333.4790,475096.2025,0.107568,3.510553e+09,4.142014e+10
240,20250731,473452.8027,476778.4380,467270.1280,468807.8897,-1.323587,3.664536e+09,4.188746e+10
241,20250801,469700.6267,477616.7526,469466.5738,477021.4323,1.752006,3.366718e+09,4.076956e+10

# 中证指数网站获取指数数据

In [9]:
import pandas as pd
import requests
# https://www.csindex.com.cn/#/indices/family/detail?indexCode=000985
url = "https://www.csindex.com.cn/csindex-home/perf/index-perf?indexCode=000300&startDate=20250803&endDate=20250804"
res = requests.get(url)
data = res.json()["data"]
pd.DataFrame(data)

,tradeDate,indexCode,indexNameCnAll,indexNameCn,indexNameEnAll,indexNameEn,open,high,low,close,change,changePct,tradingVol,tradingValue,consNumber,peg
0,20250803,000300,沪深300指数,沪深300,CSI 300 Index,CSI 300,4037.94,4070.7,4037.94,4070.7,15.77,0.39,16227.59,2959.77,300.0,12.59
1,20250804,000300,沪深300指数,沪深300,CSI 300 Index,CSI 300,4037.94,4070.7,4037.94,4070.7,15.77,0.39,16227.59,2959.77,300.0,12.59