# AKshare获取指数数据

In [1]:
import akshare as ak

stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(
    symbol="sh000016", start_date="20250101", end_date="20250801"
)
data = stock_zh_a_daily_qfq_df[
    ["date", "open", "high", "low", "close", "volume", "amount"]
].rename(
    columns={
        "open": "OPEN",
        "high": "HIGH",
        "low": "LOW",
        "close": "CLOSE",
        "volume": "VLOUME",
        "amount": "AMT",
    }
)
data["PCT_CHG"] = data["CLOSE"].pct_change() * 100

In [5]:
# 获取minbar
import akshare as ak

index_zh_a_hist_min_em_df = ak.index_zh_a_hist_min_em(
    symbol="399006",
    period="1",
    start_date="2025-08-01 09:30:00",
    end_date="2025-09-01 19:00:00",
)

In [6]:
index_zh_a_hist_min_em_df

,时间,开盘,收盘,最高,最低,成交量,成交额,均价
0,2025-08-26 09:30:00,0.00,2747.11,2747.11,2747.11,2320754,6.422030e+09,2754.488
1,2025-08-26 09:31:00,0.00,2737.23,2745.24,2737.18,9179728,2.231280e+10,2744.756
2,2025-08-26 09:32:00,0.00,2739.90,2740.63,2735.20,7204412,1.766199e+10,2743.540
3,2025-08-26 09:33:00,0.00,2741.55,2743.61,2740.70,5416484,1.343647e+10,2746.451
4,2025-08-26 09:34:00,0.00,2731.61,2742.34,2731.61,5249644,1.259495e+10,2743.368
...,...,...,...,...,...,...,...,...
1200,2025-09-01 14:56:00,2950.57,2952.04,2952.04,2950.57,1945093,4.535486e+09,2918.664
1201,2025-09-01 14:57:00,2951.51,2954.03,2954.03,2951.40,2286892,5.385786e+09,2919.668
1202,2025-09-01 14:58:00,2953.59,2953.61,2953.61,2953.59,55169,1.535180e+08,2919.903
1203,2025-09-01 14:59:00,2953.61,2953.61,2953.61,2953.61,0,0.000000e+00,2919.903
1204,2025-09-01 15:00:00,2953.61,2956.37,2956.37,2953.61,3330836,8.251685e+09,2920.480

# wind指数网站获取指数数据

In [ ]:
import requests
import pandas as pd

# https://www.windindices.com/indices/zh/IndexF9/e2d5a98547c3ee7c923a0259cee963e4
url = "https://indexapi.wind.com.cn/indicesWebsite/api/Kline?indexId=6644c422b6edae80b3c7a7d55803bc9e&period=1Y&lan=cn"
res = requests.get(url)
data = pd.DataFrame(res.json()["Result"]["data"])
data = data[["tradeDate", "open", "hight", "low", "close", "pctChange", "volume", "amount"]]

In [50]:
data.rename(
    columns={
        "tradeDate": "date",
        "open": "OPEN",
        "hight": "HIGH",
        "low": "LOW",
        "close": "CLOSE",
        "pctChange": "PCT_CHG",
        "volume": "VOLUME",
        "amount": "AMT",
    }
)

,date,OPEN,HIGH,LOW,CLOSE,PCT_CHG,VOLUME,AMT
0,20240802,221794.4531,223606.9219,219783.7344,219973.1719,-1.328707,2.275304e+09,1.232747e+10
1,20240805,218919.7813,222168.5781,215101.4688,215103.7969,-2.213622,2.472553e+09,1.318106e+10
2,20240806,217058.5469,221364.8750,217058.5469,221364.8750,2.910724,2.174654e+09,1.163576e+10
3,20240807,221867.2813,222546.5781,220096.0469,221525.6094,0.072611,2.078274e+09,1.129093e+10
4,20240808,221106.7344,222534.5156,217900.0156,221980.3594,0.205281,2.539888e+09,1.315276e+10
...,...,...,...,...,...,...,...,...
237,20250728,470595.2449,475328.4805,470525.9424,475130.5151,1.055302,3.196147e+09,3.797102e+10
238,20250729,476736.9756,476900.6297,469715.3937,474585.7004,-0.114666,3.461563e+09,4.061039e+10
239,20250730,474047.3739,476330.8669,470333.4790,475096.2025,0.107568,3.510553e+09,4.142014e+10
240,20250731,473452.8027,476778.4380,467270.1280,468807.8897,-1.323587,3.664536e+09,4.188746e+10
241,20250801,469700.6267,477616.7526,469466.5738,477021.4323,1.752006,3.366718e+09,4.076956e+10

# 中证指数网站获取指数数据

In [9]:
import pandas as pd
import requests
# https://www.csindex.com.cn/#/indices/family/detail?indexCode=000985
url = "https://www.csindex.com.cn/csindex-home/perf/index-perf?indexCode=000300&startDate=20250803&endDate=20250804"
res = requests.get(url)
data = res.json()["data"]
pd.DataFrame(data)

,tradeDate,indexCode,indexNameCnAll,indexNameCn,indexNameEnAll,indexNameEn,open,high,low,close,change,changePct,tradingVol,tradingValue,consNumber,peg
0,20250803,000300,沪深300指数,沪深300,CSI 300 Index,CSI 300,4037.94,4070.7,4037.94,4070.7,15.77,0.39,16227.59,2959.77,300.0,12.59
1,20250804,000300,沪深300指数,沪深300,CSI 300 Index,CSI 300,4037.94,4070.7,4037.94,4070.7,15.77,0.39,16227.59,2959.77,300.0,12.59

## Tushare Pro数据

In [5]:
import tushare as ts
from config import TUSHARE_TOKEN
ts.set_token(TUSHARE_TOKEN)
pro = ts.pro_api()

#获取沪深300ETF华夏510330.SH的历史分钟数据
df = pro.stk_mins(ts_code='513090.SZ', freq='1min', start_date='2025-09-01 09:00:00', end_date='2025-09-01 19:00:00')

Exception: 抱歉，您每天最多访问该接口2次，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。

In [2]:
df

,ts_code,trade_time,close,open,high,low,vol,amount
0,510330.SH,2025-09-01 15:00:00,4.683,4.683,4.683,4.682,108400.0,507623.0
1,510330.SH,2025-09-01 14:59:00,4.682,4.686,4.686,4.682,133200.0,623886.0
2,510330.SH,2025-09-01 14:58:00,4.684,4.686,4.686,4.683,225600.0,1057076.0
3,510330.SH,2025-09-01 14:57:00,4.686,4.685,4.686,4.684,501900.0,2351271.0
4,510330.SH,2025-09-01 14:56:00,4.685,4.683,4.685,4.683,147300.0,690015.0
...,...,...,...,...,...,...,...,...
236,510330.SH,2025-09-01 09:34:00,4.674,4.683,4.684,4.673,905200.0,4233411.0
237,510330.SH,2025-09-01 09:33:00,4.683,4.683,4.683,4.679,624400.0,2923338.0
238,510330.SH,2025-09-01 09:32:00,4.682,4.682,4.685,4.678,474000.0,2219168.0
239,510330.SH,2025-09-01 09:31:00,4.681,4.670,4.682,4.670,688200.0,3219907.0
240,510330.SH,2025-09-01 09:30:00,4.668,4.668,4.668,4.668,234500.0,1094646.0